Repository brhahlen/dc, pull requests merged in 2021-01, with the labels that each got.

#13 Fixed typo in help
  dc
Labels: bug, documentation

#16 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation

#17 Added pull functionality
  dc
Labels: enhancement

#18 Feature compose version check
  dc
Labels: enhancement

#19 Feature install
  README.md
  dc
Labels: enhancement

#21 Feature dc completion
  dc
  dc-completion
Labels: enhancement

#22 Feature restart stacks
  dc
  dc-completion
Labels: enhancement

#26 Typo in show_usage
  dc
Labels: bug

#27 Newline added
  dc
Labels: bug
