Repository brhahlen/dc, pull requests merged in 2024-06, with the labels that each got.

#66 Add `shell` command - basic
  CHANGELOG.md
  build-files/CHANGELOG.md
  dc
  dc-completion
Labels: enhancement

#69 Improve dc ips should support multiple ips
  CHANGELOG.md
  build-files/CHANGELOG.md
  dc
  dc-completion
Labels: improvement

#71 Fix dc help layout
  dc
Labels: bug
